version: '3'
services:
  #CLIENT
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    ports:
      - 3000:8080
    command: npm run start
